[workspace]
members = [
  "1.2_hello_world",
  "1.3_hello_cargo",
  "2_guessing_game",
  "3.1_variables",
  "3.2_data_types",
  "3.3_functions",
  "3.5_control_flow",
  "4.1_ownership",
  "4.2_references_and_borrowing",
  "4.3_slice_type",
  "5.1_structs",
]
